root: true

parserOptions:
    ecmaVersion: 8
    sourceType: module
    ecmaFeatures:
        jsx: false
        impliedStrict: true
        globalReturn: false

env:
    browser: true
    es6: true
    node: true

extends: [ "eslint:recommended", "plugin:prettier/recommended" ]
rules:
    no-console: off
    no-unused-vars: [ error, { args: none } ]
    no-var: error
    eqeqeq: error
